# Generated by Django 2.2 on 2020-12-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20201203_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='confirm_pw',
        ),
    ]
