# Generated by Django 2.2 on 2020-12-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_remove_registration_confirm_pw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='birthday',
        ),
    ]
